src/Data/ProgrammesDb/EntityRepository/ServiceRepository.php
src/Domain/Entity/Service.php
src/Mapper/ProgrammesDbToDomain/AbstractMapper.php
src/Mapper/ProgrammesDbToDomain/BroadcastMapper.php
src/Mapper/ProgrammesDbToDomain/CollapsedBroadcastMapper.php
src/Mapper/ProgrammesDbToDomain/ProgrammeMapper.php
src/Mapper/ProgrammesDbToDomain/ServiceMapper.php
src/Mapper/ProgrammesDbToDomain/VersionMapper.php
src/Service/ServicesService.php
tests/Mapper/ProgrammesDbToDomain/ProgrammeMapperTest.php

It seems `getDomainModel()` was expecting a date string in the array, but now a DateTimeImmutable is being passed in.

Datetime fix

---

src/Domain/ApplicationTime.php

`DateTimeImmutable::createFromFormat` expects a string as the second parameter. `time()` returns an int.
While ~~stealing your code~~ using your code as a great reference I've been setting strict types everywhere, so this one bit me.
Just a little bug you may encounter in future if you come to add strict types to this file.

Cast time() to a string for createFromFormat

---

src/Data/ProgrammesDb/Entity/CoreEntity.php
src/Data/ProgrammesDb/Entity/Network.php
src/Data/ProgrammesDb/Entity/RefOptions.php
src/Data/ProgrammesDb/Entity/Traits/OptionsTrait.php
tests/Data/ProgrammesDb/Entity/CoreEntityTest.php

**To test it locally**:
In project programmes-faucet:
1- change composer.json to this:
`"bbc/programmes-pages-service": "dev-isite-db-entities"`
2- Run this command to recreate the database:
`   php app/console doctrine:schema:update`
**Changes in schema:**
Added new table 'ref_options'
Added 'options' fields to core_entity and network

[isite] - db entities

---

src/Domain/Entity/Broadcast.php
src/Domain/Entity/BroadcastGap.php
tests/Domain/Entity/BroadcastGapTest.php

This is object similar to Broadcast, that can be used for handling
gaps in service transmission schedules

Add BroadcastGap domain object

---

src/Data/ProgrammesDb/Entity/RefOptions.php
tests/Data/ProgrammesDb/Entity/RefOptionsTest.php

To test follow next steps.
Faucet composer.json:
programmes-pages-service pointing this branch: `dev-update-db`
Then in faucet:
`php app/console doctrine:schema:update --dump-sql`
If you like the sql queries you can run them:
`php app/console doctrine:schema:update --force`

[isite] Update schema in ref_options table

---

src/Mapper/ProgrammesDbToDomain/CoreEntityMapper.php
src/Mapper/ProgrammesDbToDomain/MapperFactory.php
tests/Mapper/ProgrammesDbToDomain/BaseMapperTestCase.php
tests/Mapper/ProgrammesDbToDomain/BaseProgrammeMapperTestCase.php
tests/Mapper/ProgrammesDbToDomain/CoreEntityMapperMasterBrandMappingTest.php
tests/Mapper/ProgrammesDbToDomain/CoreEntityMapperOptionsMappingTest.php

It is possible that a CoreEntity that is not relatated to a MasterBrand
does have a parent that is related to a MasterBrand, for example p043m65r
In the new frontend we want these Entities that do not have an explict
MasterBrand set to try and find one from their ancestry, in the same way
that we try and inherit images.
Clifton however does not do this inheritance.
In order to not make changes to Clifton's output, add an option
"core_entity_inherit_master_brand" to the MapperFactory that allows us
to choose between these two behaviours. When consuming PagesService you
probably want to set this option to true. We have not set this to be the
default as that would constitiute a breaking change, that we don't want
to make right now.

Add option to inherit MasterBrand from parent CoreEntity

---

tests/Service/AtozTitlesService/AbstractAtozTitlesServiceTest.php
tests/Service/BroadcastsService/AbstractBroadcastsServiceTest.php

I really would like to see this way of mocking more. Is simpler, and less verbose.
Why!?
With createMock() you need at least two lines, to mock a method. 
$stubBroadcast = $this->createMock(Broadcast::class);
$stubBroadcast->method('getPid')->willReturn(new Pid($dbData['pid']));
With createConfiguredMock():
$this->createConfiguredMock(AtozTitle::class,['getFirstletter' => $dbData['firstLetter']])
Even if you format it is still more compact (no methods around, no arrows...):
$this->createConfiguredMock(
AtozTitle::class,
['getFirstletter' => $dbData['firstLetter']]
);

mocking less verbose

---

src/Data/ProgrammesDb/Entity/Promotion.php
src/Data/ProgrammesDb/Entity/RelatedLink.php
src/Data/ProgrammesDb/EntityRepository/PromotionRepository.php
src/Domain/Entity/Promotion.php
src/Mapper/ProgrammesDbToDomain/PromotionMapper.php
tests/Data/ProgrammesDb/EntityRepository/PromotionRepository/FindActivePromotionsByContextTest.php
tests/DataFixtures/ORM/PromotionsFixture.php
tests/Domain/Entity/PromotionTest.php
tests/Mapper/ProgrammesDbToDomain/PromotionMapperTest.php

Whenever we display promotions we always want to show the related links
attached to them. As there are very few promos with more than one related
link it is cheaper to request them in the same query as the promos, rather
than do a two step hydration process.
* Add a OneToMany 'relatedLinks' relationship into the Promotion Doctrine
entity (this is the inverse of the relationship on the RelatedLink).
This does not require a DB change, it is just a mapping update.
* Add an array of related links to the Promotion's constructor, this may
be null to signify the Related Links were unfetched (this is the same
as how Genres/Formats on a Programme works)
* Update the PromotionMapper to construct Promotions with Related Links
if they were requested.
* Request Related Links in …

Attach RelatedLinks to Promotions

---

src/Mapper/ProgrammesDbToDomain/PromotionMapper.php

The new phpstan is complaining, failing in the build with the next message:
```
------ --------------------------------------------------------------------------------------------------------------------------------------------
Line   src/Mapper/ProgrammesDbToDomain/PromotionMapper.php
------ --------------------------------------------------------------------------------------------------------------------------------------------
87     Return typehint of method BBC\ProgrammesPagesService\Mapper\ProgrammesDbToDomain\PromotionMapper::getRelatedLinksModels() has invalid type
BBC\ProgrammesPagesService\Mapper\ProgrammesDbToDomain\RelatedLink.
```
This is the fix

fix phpstan master build

---

src/Cache/Cache.php
src/Cache/CacheInterface.php
src/Service/BroadcastsService.php
tests/Service/BroadcastsService/FindOnNowByServiceTest.php

- Set max cache time to 300s
- Add function flushOnNowByService so we can flush it when an stale object still in memory and is not longer valid
Frontend changes to use flushOnNowByService
https://github.com/bbc/programmes-frontend/commit/01d5685fbec0814446ce3797f1527d13919d9d0c

PROGRAMMES-6052 findOnNowByService cache issues

---

src/Data/ProgrammesDb/EntityRepository/CoreEntityRepository.php
tests/Data/ProgrammesDb/EntityRepository/CoreEntityRepository/FindByPidsTest.php

SQL makes no claims about the order of what it returns. Make sure
findByPids(['pid1','pid3','pid2']) returns the entities represented by
those pids in that order.
I'm fairly sure it makes more sense to do this ordering here rather than in ProgrammesService->findByPids. What do you think?

Order CoreEntityRepository->findByPids results based on pids passed in

---

src/Data/ProgrammesDb/EntityRepository/RelatedLinkRepository.php
src/Service/RelatedLinksService.php
tests/Service/RelatedLinksService/FindByRelatedToProgrammeTest.php

Allow for passing in an array of related link types.
I don't think filter by type requires an index, as we're already
filtering by the related_to id, which reduces the result set down to
less than 50 results in all cases (and less than 20 results in all but
45 cases).
Fixes PROGRAMMES-6221.
---
This adds a parameter in the middle of the arg list for `findByRelatedToProgramme`, which is technically a breaking change, however everywhere we call that function (only in frontend and clifton) we never explicitly state limit/page arguments. So I'm happy with pulling a fast one on this.

Allow RelatedLinksService->findByRelatedToProgramme() filter by link type

---

phpstan.neon
src/Data/ProgrammesDb/Entity/RelatedLink.php
src/Domain/Entity/RelatedLink.php
src/Mapper/ProgrammesDbToDomain/RelatedLinkMapper.php
tests/Domain/Entity/RelatedLinkTest.php
tests/Mapper/ProgrammesDbToDomain/RelatedLinkMapperTest.php

The external field from PIPs doesn't seem to be used as diligently as we
hoped. Instead work out if a Related Link is external or not on our own.
A link is considered external if the url is on bbc.co.uk or bbc.com or
one of their subdomains.
This is done lazily so that we can try and avoid regex calls to parse
the url if they are not needed.
Add getHost to RelatedLink.
---
getHost is needed as related link lists in v2 shows the host if the link is external

Calculate isExternal within the RelatedLink domain object

---

src/Data/ProgrammesDb/EntityRepository/VersionRepository.php
src/Domain/Entity/Episode.php
src/Domain/Entity/ProgrammeItem.php
src/Mapper/ProgrammesDbToDomain/CoreEntityMapper.php
src/Service/VersionsService.php
tests/Data/ProgrammesDb/EntityRepository/VersionRepository/FindAvailableByProgrammeItemTest.php
tests/DataFixtures/ORM/VersionFixture.php
tests/Domain/Entity/ClipTest.php
tests/Domain/Entity/EpisodeTest.php
tests/Mapper/ProgrammesDbToDomain/CoreEntityMapperTest.php
tests/Service/VersionsService/FindAvailableByProgrammeItemTest.php

Fetching the downloadable version is not possible in findByPidFull when the episode gets first fetched in programmes-frontend because we don't know what type of CoreEntity we're fetching, so Doctrine doesn't fetch that column. Any ideas on how to fetch it?

Adding media set mapping to domain entity

---

src/Data/ProgrammesDb/EntityRepository/SegmentEventRepository.php

Added missing "order by". The offset from the program start is the second most important field to order by and this is how v2 does the ordering

PROGRAMMES-6261 - Segment events order

---

src/Mapper/ProgrammesDbToDomain/OptionsMapper.php
tests/Mapper/ProgrammesDbToDomain/CachingTest.php
tests/Mapper/ProgrammesDbToDomain/OptionsMapperTest.php

Ticket: https://jira.dev.bbc.co.uk/browse/PROGRAMMES-6556
There are other places projectID is used, but these are all variables/properties that don't affect the result the frontend uses. I have left these as is for now (Given some of them are in places where everything is camelCased, and doing this would make one variable snake_cased), but if people feel it's beneficial to do those too, then I'll update them too.
This should fix this issue when on test DB: https://sandbox.bbc.co.uk/programmes/b04ww8fq/profiles (No project_space on the PID, and it wasn't looking above it).

[PROGRAMMES-6556] Renamed a remaining projectID to project_space

---

src/Service/SegmentEventsService.php

Currently segment events are cached for 5 minutes so it takes some time to display relevant information for live shows, Changing the TTL to 1 minute should dispaly more relevany segments information

Decrease TTL for Segment events

---

src/Data/ProgrammesDb/Entity/MasterBrand.php
src/Domain/Entity/Episode.php
src/Domain/Entity/MasterBrand.php
src/Domain/Entity/ProgrammeItem.php
src/Domain/Entity/Unfetched/UnfetchedMasterBrand.php
src/Mapper/ProgrammesDbToDomain/MasterBrandMapper.php
tests/Data/ProgrammesDb/Entity/MasterBrandTest.php
tests/Domain/Entity/ClipTest.php
tests/Domain/Entity/EpisodeTest.php
tests/Domain/Entity/MasterBrandTest.php
tests/Mapper/ProgrammesDbToDomain/MasterBrandMapperTest.php

Changes for Faucet and Frontend to enable sending only certain masterbrands to playspace.
* New field on Masterbrand entity for faucet. Push that field into domain objects for Frontend
* New method on ProgrammeItem, isPlayable (is that shit naming?) to test whether something will play out in practice, not just whether the media is streamable.

Programmes 6640 playspace masterbrands

---

src/Data/ProgrammesDb/EntityRepository/PromotionRepository.php

A promotion is related to and image or a core entity, this changes exclude promotions that are related to an embargoed image or core entity. This is required because the promotion can't get the related embargoed item and fail to display generating a 500
A clarification about the `Where`, becuae this is doing a left join, the non joined table will evaluate fields as null so `promotionOfX.isEmbargoed = 0` will never be true for the non joined one

PROGRAMMES-6691 fix promotion embargoed

---

src/Data/ProgrammesDb/EntityRepository/CoreEntityRepository.php
src/Service/ProgrammesService.php
tests/Data/ProgrammesDb/EntityRepository/CoreEntityRepository/FindAllTest.php
tests/Data/ProgrammesDb/EntityRepository/CoreEntityRepository/FindChildrenSeriesWithClipsByParentTest.php
tests/Data/ProgrammesDb/EntityRepository/CoreEntityRepository/FindEpisodeGuideChildrenTest.php
tests/DataFixtures/ORM/MongrelsFixture.php

Filter by showing series with no available clips.
I have created a function very similar to `findChildrenSeriesByParent`, I have decided to it this way instead of editing the existing function because it is used by v2 and editing the function for this 2 different cases without changing the function name doesn't seems clear.
This funtion will be used by this change https://github.com/bbc/programmes-frontend/compare/PROGRAMMES-6981-only-series-with-clips
Also I noticed that a unitest not related to this changes `FindBySegmentTest.php:37` fails in my host but works fine in the sandbox, same issue happen in master

PROGRAMMES-6981 Clips list page 

---

src/Data/ProgrammesDb/Entity/CoreEntity.php
src/Data/ProgrammesDb/EntityRepository/CoreEntityRepository.php
tests/Data/ProgrammesDb/EntityRepository/CoreEntityRepository/FindTleosByCategoryTest.php

https://jira.dev.bbc.co.uk/browse/PROGRAMMES-6957
https://jira.dev.bbc.co.uk/browse/PROGRAMMES-6959
Changes:
- Add a new compound index to CoreEntity to speed up TLEO category queries
- Update `findTleosByCategory` order for the new category page

Category pages

---

src/Data/ProgrammesDb/EntityRepository/CoreEntityRepository.php
src/Data/ProgrammesDb/EntityRepository/PromotionRepository.php
src/Service/CoreEntitiesService.php
src/Service/PromotionsService.php
src/Service/RelatedLinksService.php
tests/Data/ProgrammesDb/EntityRepository/PromotionRepository/FindActivePromotionsByContextTest.php
tests/Service/PromotionsService/FindActivePromotionsByContextTest.php
tests/Service/PromotionsService/FindActivePromotionsByEntityGroupedByTypeTest.php

* Add query to pull all CoreEntity members of a group, arranged by position
* The query to retrieve promotions with a limit wasn't respecting the limit. Removed the parameter to set a limit, renamed the function
* Added a new query to retrieve promotions with a limit
* Modified related link query to accept all CoreEntities, not just programmes.

PROGRAMMES-7050: Queries for Collection Page

---

composer.json
composer.lock
phpstan.neon
src/Data/ProgrammesDb/EntityRepository/AtozTitleRepository.php
src/Data/ProgrammesDb/EntityRepository/BroadcastRepository.php
src/Data/ProgrammesDb/EntityRepository/CollapsedBroadcastRepository.php
src/Data/ProgrammesDb/EntityRepository/PromotionRepository.php
src/Data/ProgrammesDb/EntityRepository/SegmentEventRepository.php
src/Data/ProgrammesDb/EntityRepository/VersionRepository.php
tests/doctrine-bootstrap.php

This fixes (mostly by upgrading dependencies) unit test breakage on PHP7.3+. Shouldn't have any effect on functionality or compatibility with older PHP versions.

Fix tests for PHP7.3

---

src/Data/ProgrammesDb/Entity/RefAvailabilityMabel.php

Adding temporary table to store Mabel / APPW availability data (for comparison)
https://jira.dev.bbc.co.uk/browse/DATCAP-481
```
CREATE TABLE ref_availability_mabel (
id INT AUTO_INCREMENT NOT NULL, 
version_id INT NOT NULL, 
programme_item_id INT NOT NULL, 
media_set_id INT NOT NULL, 
status VARCHAR(32) NOT NULL, 
type VARCHAR(64) NOT NULL, 
scheduled_start DATETIME NOT NULL, 
scheduled_end DATETIME DEFAULT NULL, 
actual_start DATETIME DEFAULT NULL, 
created_at DATETIME NOT NULL, 
updated_at DATETIME NOT NULL, 
INDEX IDX_A5AAA35C4BBC2705 (version_id), 
INDEX IDX_A5AAA35CC9CC1FD5 (programme_item_id), 
INDEX IDX_A5AAA35CAC8297C6 (media_set_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET UTF8 COLLATE `UTF8_unicode_ci` ENGINE = InnoDB
ALTER TABLE ref_availability_mabel ADD CONSTRAINT …
```

DATCAP-481: adding ref_availability_mabel entity

---

src/Data/ProgrammesDb/Entity/Image.php
tests/Data/ProgrammesDb/Entity/ImageTest.php

[DATCAP-1031](https://jira.dev.bbc.co.uk/browse/DATCAP-1031)
- Added two new properties for Image entity: height and width
- Added getters and setters for the two new properties
Brings the Image Entity into line with the database, now possessing a height and width property. Will be used in Faucet to allow image height and width to be ingested into the Programmes DB
Unit tests are passing

DATCAP-1031: Update Image Entity

---

src/Domain/Enumeration/ContactMediumEnum.php

In support of https://jira.dev.bbc.co.uk/browse/DATCAP-1142, need to add a new enum so it can be used in Faucet to ingest the new privacy policy option into the DB.

DATCAP-1142: Add Privacy Policy as a valid contact type
