src/Service/AbstractService.php
src/Service/AtozTitlesService.php
src/Service/BroadcastsService.php
src/Service/CategoriesService.php
src/Service/CollapsedBroadcastsService.php
src/Service/ContributionsService.php
src/Service/ContributorsService.php
src/Service/LoggingServiceFactory.php
src/Service/NetworksService.php
src/Service/ProgrammesService.php
src/Service/RelatedLinksService.php
src/Service/SegmentEventsService.php
src/Service/SegmentsService.php
src/Service/ServiceFactory.php
src/Service/ServicesService.php
src/Service/VersionsService.php
tests/Service/LoggingServiceFactoryTest.php

5516 cache item pool interface

---

src/Data/ProgrammesDb/Entity/Network.php
src/Data/ProgrammesDb/Entity/ProgrammeItem.php
src/Data/ProgrammesDb/Entity/RefAvailability.php
src/Domain/Entity/Network.php
src/Domain/Entity/ProgrammeItem.php
src/Domain/Enumeration/AvailabilityStatusEnum.php
src/Domain/Enumeration/MediaTypeEnum.php
src/Domain/Enumeration/NetworkMediumEnum.php
tests/Data/ProgrammesDb/Entity/RefAvailabilityTest.php

This saves us having to define the list of valid values in multiple
places

Add a utility methods to get valid values from enums

---

src/Domain/Entity/Programme.php

Any objections? Please say there are no objections.

Add isRadio() and isTv() methods to programme

---

src/Data/ProgrammesDb/EntityRepository/BroadcastRepository.php

https://jira.dev.bbc.co.uk/browse/PROGRAMMES-5704

Fix empty schedule

---

src/Domain/Entity/Collection.php
src/Domain/Entity/Contribution.php
src/Domain/Entity/Franchise.php
src/Domain/Entity/Gallery.php
src/Domain/Entity/Group.php
src/Domain/Entity/Season.php
src/Domain/Entity/Unfetched/UnfetchedGroup.php
src/Mapper/ProgrammesDbToDomain/ContributionMapper.php
src/Mapper/ProgrammesDbToDomain/GroupMapper.php
src/Mapper/ProgrammesDbToDomain/MapperFactory.php
src/Service/GroupsService.php
src/Service/ServiceFactory.php
tests/Domain/Entity/CollectionTest.php
tests/Domain/Entity/ContributionTest.php
tests/Domain/Entity/FranchiseTest.php
tests/Domain/Entity/GalleryTest.php
tests/Domain/Entity/SeasonTest.php
tests/Mapper/ProgrammesDbToDomain/ContributionMapperTest.php
tests/Mapper/ProgrammesDbToDomain/MapperFactoryTest.php
tests/Service/ServiceFactoryTest.php

https://jira.dev.bbc.co.uk/browse/PROGRAMMES-4960

4960 Adding group models

---

src/Domain/Entity/Brand.php
src/Domain/Entity/Clip.php
src/Domain/Entity/Collection.php
src/Domain/Entity/CoreEntity.php
src/Domain/Entity/Episode.php
src/Domain/Entity/Franchise.php
src/Domain/Entity/Gallery.php
src/Domain/Entity/Group.php
src/Domain/Entity/ProgrammeContainer.php
src/Domain/Entity/Season.php
src/Domain/Entity/Series.php
tests/Domain/Entity/ProgrammeTest.php

https://jira.dev.bbc.co.uk/browse/PROGRAMMES-5786

Adding useful methods for CoreEntity

---

composer.lock
src/Service/ProgrammesAggregationService.php

Housekeeping

---

src/Domain/Entity/CoreEntity.php
src/Domain/Entity/Image.php
src/Domain/Entity/PromotableInterface.php
src/Domain/Entity/Promotion.php
src/Domain/Entity/PromotionableInterface.php

First PR for ticket:
'Build Domain Models and DB->Domain Mapper for Promotions'
This PR only includes the domain entity for promotions.

Model promotions

---

src/Mapper/ProgrammesDbToDomain/CoreEntityMapper.php

This saves a few string comparisons.
Check programme types before groups types as that's a more likely
outcome.

Use explicit functions for checking type in CoreEntityMapper

---

composer.json
composer.lock
phpcs.xml.dist
src/Data/ProgrammesDb/EntityRepository/Traits/ParentTreeWalkerTrait.php
tests/AbstractDatabaseTest.php
tests/Data/ProgrammesDb/EntityRepository/BroadcastRepository/FindAllByServiceAndDateRangeTest.php
tests/Data/ProgrammesDb/EntityRepository/CollapsedBroadcastRepository/FindByStartAndProgrammeItemIdTest.php
tests/Data/ProgrammesDb/EntityRepository/CoreEntityRepository/CategoryResolutionTest.php
tests/Data/ProgrammesDb/EntityRepository/CoreEntityRepository/FindAdjacentProgrammeByPositionTest.php
tests/Data/ProgrammesDb/EntityRepository/CoreEntityRepository/ParentResolutionTest.php
tests/DataFixtures/ORM/BroadcastsEmbargoFixture.php
tests/DataFixtures/ORM/BroadcastsWithCategoriesFixture.php
tests/DataFixtures/ORM/CollapsedBroadcastsWithBroadcastsFixture.php
tests/DataFixtures/ORM/TleosByCategoryFixture.php
tests/Mapper/ProgrammesDbToDomain/AtozTitleMapperTest.php
tests/Mapper/ProgrammesDbToDomain/BaseCoreEntityMapperTestCase.php
tests/Mapper/ProgrammesDbToDomain/CachingTest.php
tests/Mapper/ProgrammesDbToDomain/CoreEntityMapperOptionsMappingTest.php
tests/Mapper/ProgrammesDbToDomain/VersionMapperTest.php

Migrate phpcs standard to symfony 3

Phpcs coding style symfony3

---

src/Mapper/ProgrammesDbToDomain/CategoryMapper.php
src/Mapper/ProgrammesDbToDomain/CoreEntityMapper.php
tests/Mapper/ProgrammesDbToDomain/CoreEntityMapperTest.php

* Adding tests for building Groups in CoreEntityMapper
* Refactoring how we get get models for CoreEntities to avoid having dead code and duplicate isset checks

Mapper improvements

---

src/Domain/Entity/Promotion.php
tests/Domain/Entity/PromotionTest.php

I forgot to add tests for promotion entity domain.

promotion domain tests

---

src/Mapper/ProgrammesDbToDomain/MapperFactory.php
src/Mapper/ProgrammesDbToDomain/PromotionMapper.php
tests/Mapper/ProgrammesDbToDomain/PromotionMapperTest.php

once that promotions-repository is ready then the mapper is necessary (THIS PR)

promotions-mapper

---

src/Data/ProgrammesDb/EntityRepository/PromotionRepository.php
tests/Data/ProgrammesDb/EntityRepository/PromotionRepository/FindActiveSuperpromotionsByPidTest.php

Writing now my tests for the service I realized that "find.....ByPid()" was not the appropiate name for this function.

renamed function in promotion repository

---

src/Data/ProgrammesDb/EntityRepository/PromotionRepository.php
tests/Data/ProgrammesDb/EntityRepository/PromotionRepository/FindActivePromotionsByContextTest.php
tests/Data/ProgrammesDb/EntityRepository/PromotionRepository/FindActivePromotionsByPidTest.php
tests/Data/ProgrammesDb/EntityRepository/PromotionRepository/FindActiveSuperpromotionsByAncestryTest.php

Improved query removing one unnecessary JOIN

Promotion query improvement

---

src/Data/ProgrammesDb/Entity/RefIsiteOptions.php
tests/Data/ProgrammesDb/Entity/RefIsiteOptionsTest.php

Needed as part of https://jira.dev.bbc.co.uk/browse/PROGRAMMES-5624

Adding parentProjectId to RefIsiteOptions

---

src/Data/ProgrammesDb/Entity/RefIsiteOptions.php

Allowing a null parentProjectId

---

tests/AbstractServiceTest.php
tests/Service/BroadcastsService/AbstractBroadcastsServiceTest.php
tests/Service/BroadcastsService/FindByServiceAndDateRangeTest.php
tests/Service/BroadcastsService/FindByVersionTest.php

Main changes:
- Added extra tests to test pagination on FindByVersionTest.php
- Removed unused function broadcastsFromDbData() (is not used anymore in order to get more visibility on tests)
- Modified explicit dates for dynamics "+/-1year"
- Simplified some tests

[Tests tidy] Broadcasts service 

---

tests/Service/AtozTitlesService/AbstractAtozTitlesServiceTest.php
tests/Service/AtozTitlesService/CountAvailableTleosByFirstLetterTest.php
tests/Service/AtozTitlesService/CountTleosByFirstLetterTest.php
tests/Service/AtozTitlesService/FindAllLettersTest.php
tests/Service/AtozTitlesService/FindAvailableTleosByFirstLetterTest.php
tests/Service/AtozTitlesService/FindTleosByFirstLetterTest.php

Main changes:
- changes similar to broadcastService tests
- moved different functions under test to theirs own test class

[Tests tidy] atoztitles service

---

src/Data/ProgrammesDb/EntityRepository/ServiceRepository.php

Can't see this being used any where.

Removing findBySids method

---

src/Domain/Entity/Promotion.php
tests/Domain/Entity/PromotionTest.php

Its the Synopsis we pretty much always want.
Fix a tiny spacing issue in a comment while I'm in there

Add getShortSynopsis to Promotion

---

README.md

Added in proper copyright.  
Renamed License files.  
Added link to License file.

Updating License info

---

src/Service/CollapsedBroadcastsService.php
tests/Service/CollapsedBroadcastsService/AbstractCollapsedBroadcastServiceTest.php
tests/Service/CollapsedBroadcastsService/CountUpcomingByProgrammeTest.php
tests/Service/CollapsedBroadcastsService/FilterCategoriesByBroadcastedDateTest.php
tests/Service/CollapsedBroadcastsService/FindBroadcastYearsAndMonthsByProgrammeTest.php
tests/Service/CollapsedBroadcastsService/FindByCategoryAndEndAtDateRangeTest.php
tests/Service/CollapsedBroadcastsService/FindByCategoryAndStartAtDateRangeTest.php
tests/Service/CollapsedBroadcastsService/FindByProgrammeAndMonthTest.php
tests/Service/CollapsedBroadcastsService/FindDaysByCategoryInDateRangeTest.php
tests/Service/CollapsedBroadcastsService/FindPastByProgrammeTest.php
tests/Service/CollapsedBroadcastsService/FindUpcomingByProgrammeTest.php

- New test class for method: countUpcomingByProgramme()
- Added additional comments in original service (too much?, is it OK?)
- Added additional tests for some cases (boundaries)

CollapsedBroadcastsService

---

src/Domain/Entity/Broadcast.php
src/Domain/Entity/BroadcastGap.php
src/Domain/Entity/BroadcastInfoInterface.php

It would be nice to be able to typehint either Broadcasts or Broadcast gaps.  
Do people prefer an interface or an abstract class?

PROGRAMMES-5864 Adding interface for Broadcast and BroadcastGap

---

phpstan.neon
tests/Service/ContributorsService/AbstractContributorsServiceTest.php
tests/Service/ContributorsService/FindAllMostPlayedTest.php
tests/Service/ContributorsService/FindByMusicBrainzIdTest.php

- deleted unnecesary rule to ignore in PHPstan cause is not happening anymore.

PROGRAMMES-5824 Tests contributorsService

---

src/Data/ProgrammesDb/EntityRepository/PromotionRepository.php
src/Domain/Entity/CoreEntity.php

* Make CoreEntity->getNetwork() throw a useful unfetched exception
* Add extra joins when requesting Promotions

Add extra joins to Promotion Repo

---

src/Data/ProgrammesDb/Entity/CoreEntity.php
src/Domain/Entity/Genre.php
tests/Domain/Entity/GenreTest.php

Actually part of https://jira.dev.bbc.co.uk/browse/PROGRAMMES-5757

PROGRAMMES-5756-footer

---

src/Domain/Entity/Genre.php

Improved efficiency, related to displaying programme genre information in:
https://jira.dev.bbc.co.uk/browse/PROGRAMMES-5757

PROGRAMMES-5757 Genre urlKeyHierarchy 

---

src/Data/ProgrammesDb/EntityRepository/CoreEntityRepository.php
src/Service/ProgrammesAggregationService.php
tests/Data/ProgrammesDb/EntityRepository/CoreEntityRepository/FindDescendantsByTypeTest.php
tests/Service/ProgrammesAggregationService/FindDescendantClipsTest.php
tests/Service/ProgrammesAggregationService/FindStreamableDescendantEpisodesTest.php

To fix this problem: https://jira.dev.bbc.co.uk/browse/PROGRAMMES-5737?focusedCommentId=3613303&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-3613303

Changing streamable episode ordering

---

src/Mapper/ProgrammesDbToDomain/OptionsMapper.php
tests/Mapper/ProgrammesDbToDomain/OptionsMapperTest.php

These got moved into Faucet (https://github.com/bbc/programmes-faucet/blob/master/src/DenormMapper/IsiteOptionsMapper.php#L164-L188), so we don't need to run it here anymore

Normalizing options

---

src/Data/ProgrammesDb/Entity/RefIsiteOptions.php

We want to ingest now contact data from isite. So far we only have ```admin``` and ```local```, this PR is to support a new type: ```contact```

updated ref isite options entity

---

src/Data/ProgrammesDb/EntityRepository/CoreEntityRepository.php
src/Service/ProgrammesService.php
tests/Data/ProgrammesDb/EntityRepository/CoreEntityRepository/FindByPidsTest.php
tests/Service/ProgrammesService/FindByPidsTest.php

Added findByPids to ProgrammesService, for RecEng, which returns a list of pids. This enables us to get an array of Programmes for an array of pids

Add findByPids

---

src/Data/ProgrammesDb/EntityRepository/NetworkRepository.php

- get network if there is not defaultService when calling findByUrlKeyWithDefaultService
Requires https://github.com/bbc/programmes-frontend/pull/310

PROGRAMMES-6061

---

src/Data/ProgrammesDb/Entity/ProgrammeItem.php
src/Domain/ValueObject/PartialDate.php
tests/Domain/ValueObject/PartialDateTest.php

Schema change for On Demand Sort Date. Changes to PartialDate.

---

src/Mapper/ProgrammesDbToDomain/OptionsMapper.php

bbc_site option now is cascade

bbc_site option now is cascade

---

src/Domain/Entity/Broadcast.php
src/Domain/Entity/BroadcastGap.php
src/Domain/Entity/BroadcastInfoInterface.php
src/Domain/Entity/CollapsedBroadcast.php
src/Domain/Entity/SingleServiceBroadcastInfoInterface.php

I want a Broadcast and a CollapsedBroadcast to extend a common interface so that I can typehint it in programmes-frontend.
Is everyone happy with the naming I have chosen?

Re-jigging interfaces to allow an interface to get broadcast start times for both Broadcasts and CollapsedBroadcasts

---

src/Data/ProgrammesDb/EntityRepository/CoreEntityRepository.php
src/Service/ProgrammesAggregationService.php
tests/Data/ProgrammesDb/EntityRepository/CoreEntityRepository/CountStreamableDescendantsByTypeTest.php
tests/DataFixtures/ORM/TleosByCategoryFixture.php

Required as part of https://jira.dev.bbc.co.uk/browse/PROGRAMMES-6141

PROGRAMMES-6141 Allow counting of Episodes

---

src/Service/ProgrammesAggregationService.php

https://jira.dev.bbc.co.uk/browse/PROGRAMMES-6230

Adding countStreamableDescendantClips method

---

src/Data/ProgrammesDb/EntityRepository/VersionRepository.php
src/Service/VersionsService.php
tests/Data/ProgrammesDb/EntityRepository/VersionRepository/FindStreamableByProgrammeItemTest.php
tests/Service/VersionsService/FindStreamableByProgrammeItemTest.php

As part of https://jira.dev.bbc.co.uk/browse/PROGRAMMES-6214

Allowing querying for only streamable versions

---

src/Data/ProgrammesDb/EntityRepository/CoreEntityRepository.php

https://jira.dev.bbc.co.uk/browse/PROGRAMMES-6215

Fetching masterbrand, network and parents

---

src/Data/ProgrammesDb/EntityRepository/CollapsedBroadcastRepository.php
src/Service/CollapsedBroadcastsService.php
tests/Data/ProgrammesDb/EntityRepository/CollapsedBroadcastRepository/FindByProgrammeTest.php
tests/Service/CollapsedBroadcastsService/FindByProgrammeWithFullServicesOfNetworksListTest.php

As part of https://jira.dev.bbc.co.uk/browse/PROGRAMMES-6276
Example viewable here: https://www.bbc.co.uk/programmes/b0082trb

Find Collapsed Broadcasts by Programme

---

src/Data/ProgrammesDb/EntityRepository/CoreEntityRepository.php

https://jira.dev.bbc.co.uk/browse/PROGRAMMES-6285
This fixes the error. Not sure if it's the correct way to solve the problem though.

Fixing error retrieving masterbrand

---

src/Data/ProgrammesDb/EntityRepository/CollapsedBroadcastRepository.php
tests/Data/ProgrammesDb/EntityRepository/CollapsedBroadcastRepository/FindByProgrammeTest.php

Acting on these comments: https://github.com/bbc/programmes-pages-service/pull/236#discussion_r176436334
I believe that is what was asked for.

Removing programmeItem info from query

---

src/Data/ProgrammesDb/EntityRepository/CoreEntityRepository.php
src/Service/GroupsService.php
tests/Service/GroupsService/AbstractGroupsServiceTest.php
tests/Service/GroupsService/FindByCoreEntityMembershipTest.php

Needed for https://jira.dev.bbc.co.uk/browse/PROGRAMMES-6279

PROGRAMMES-6279 collections

---

src/Data/ProgrammesDb/EntityRepository/CoreEntityRepository.php

V2 was ordered by PID
https://jira.dev.bbc.co.uk/browse/PROGRAMMES-6279

Ordering collections in the same way as V2

---

src/Service/GroupsService.php

Acting on PR review from a different timezone: https://github.com/bbc/programmes-pages-service/pull/239#pullrequestreview-107797728

Acting on PR comments

---

src/Data/ProgrammesDb/EntityRepository/SegmentEventRepository.php
src/Service/SegmentEventsService.php
tests/Service/SegmentEventsService/FindByProgrammeForCanonicalVersionTest.php

Part of https://jira.dev.bbc.co.uk/browse/PROGRAMMES-6434

Adding canonical version query

---

src/Data/ProgrammesDb/EntityRepository/VersionRepository.php
src/Service/ProgrammesService.php
src/Service/VersionsService.php

Env: Test
Outcome: the query is fast enough to not be worried about
| Query_ID | Duration   | Query                                                                                                                                                                                                                                          
------------------------------------------------------------------------+
|        1 | 0.00116750 | SELECT SQL_NO_CACHE c0_.id AS id_0, c0_.pid ... |
|        2 | 0.00102600 | SELECT SQL_NO_CACHE c0_.id AS id_0, c0_.pid... |
|        3 | 0.00139400 | SELECT SQL_NO_CACHE c0_.id AS id_0, c0_.pid... |
|        4 | 0.00104475 | SELECT SQL_NO_CACHE c0_.id AS id_0, c0_.pid... |
|        5 | 0.00120500 | SELECT SQL_NO_CACHE c0_.id AS id_0, c0_.pid... |
|        6 | …

[No Ticket][new] - Added new query to fetch in once all the needed versions

---

src/Data/ProgrammesDb/EntityRepository/VersionRepository.php
tests/DataFixtures/ORM/VersionFixture.php

https://jira.dev.bbc.co.uk/browse/PROGRAMMES-6524?focusedCommentId=3956302&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-3956302

PROGRAMMES-6524 Updating list of versions to consider alternate

---

src/Data/ProgrammesDb/Entity/Podcast.php

https://jira.dev.bbc.co.uk/browse/PROGRAMMES-6511

Adding unique index on podcast core entity id

---

src/Data/ProgrammesDb/EntityRepository/PromotionRepository.php

https://jira.dev.bbc.co.uk/browse/PROGRAMMES-6525

PROGRAMMES-6525 Avoid entity promoting itself

---

src/Service/CoreEntitiesService.php

https://jira.dev.bbc.co.uk/browse/PROGRAMMES-6507

PROGRAMMES-6507 Adding Gallery Content Block

---

src/Data/ProgrammesDb/EntityRepository/CoreEntityRepository.php
src/Service/ProgrammesAggregationService.php

Needed by https://github.com/bbc/programmes-frontend/pull/810

PROGRAMMES-6707 - Count method

---

src/Domain/ValueObject/PartialDate.php
tests/Domain/ValueObject/PartialDateTest.php

https://jira.dev.bbc.co.uk/browse/PROGRAMMES-6733

PROGRAMMES-6733 - added hasMonth() and hasDay() to PartialDate

---

src/Data/ProgrammesDb/EntityRepository/CollapsedBroadcastRepository.php
src/Data/ProgrammesDb/EntityRepository/CoreEntityRepository.php
src/Data/ProgrammesDb/EntityRepository/Traits/ParentTreeWalkerTrait.php
src/Data/ProgrammesDb/EntityRepository/VersionRepository.php
src/Service/VersionsService.php
tests/Data/ProgrammesDb/EntityRepository/CoreEntityRepository/FindByPidFullTest.php

https://jira.dev.bbc.co.uk/browse/PROGRAMMES-6671

Programmes-6671: episodes downloads view

---

src/Data/ProgrammesDb/EntityRepository/ImageRepository.php
src/Service/ImagesService.php

Part of:
https://jira.dev.bbc.co.uk/browse/PROGRAMMES-6736

Render gallery page

---

src/Data/ProgrammesDb/Entity/Programme.php
src/Data/ProgrammesDb/EntityRepository/BroadcastRepository.php

https://jira.dev.bbc.co.uk/browse/PROGRAMMES-6754

PROGRAMMES-6754 - hide barkers and off-airs

---

src/Data/ProgrammesDb/EntityRepository/CoreEntityRepository.php

https://jira.dev.bbc.co.uk/browse/PROGRAMMES-6937

PROGRAMMES-6937 - added resolveParents for A to Z search

---

phpstan.neon
src/Data/ProgrammesDb/EntityRepository/CategoryRepository.php
src/Domain/Entity/Category.php
src/Domain/Entity/Format.php
src/Domain/Entity/Genre.php
tests/Domain/Entity/GenreTest.php

https://jira.dev.bbc.co.uk/browse/PROGRAMMES-6958

PROGRAMMES-6958 - improve domain object for categories

---

src/Data/ProgrammesDb/EntityRepository/CategoryRepository.php
src/Domain/Entity/Category.php
src/Domain/Entity/Format.php
src/Domain/Entity/Genre.php
src/Mapper/ProgrammesDbToDomain/CategoryMapper.php
src/Service/CategoriesService.php
tests/Service/CategoriesService/FindGenresTest.php

https://jira.dev.bbc.co.uk/browse/PROGRAMMES-6731

PROGRAMMES-6731 - get top level genres and their children

---

src/Data/ProgrammesDb/EntityRepository/CoreEntityRepository.php
src/Service/CoreEntitiesService.php

https://jira.dev.bbc.co.uk/browse/PROGRAMMES-7051

PROGRAMMES-7051 - count by group for collection pages

---

src/Data/ProgrammesDb/EntityRepository/CollapsedBroadcastRepository.php
src/Data/ProgrammesDb/EntityRepository/CoreEntityRepository.php
src/Service/CollapsedBroadcastsService.php
src/Service/CoreEntitiesService.php

This isn't going to be the easiest PR to understand. 
Performance of these queries without making major changes to data structures requires some fairly funky SQL that doctrine won't implement in DQL, hence native queries and some slightly unusual structures. 
Probably easiest to just ask if you want this explained.

PROGRAMMES-7087: Queries for season page

---

src/Data/ProgrammesDb/EntityRepository/CategoryRepository.php

Prevent duplicate categories from blowing up doctrine with a limit statement

---

composer.lock
src/Domain/Enumeration/ContactMediumEnum.php
src/Domain/ValueObject/UGCContactDetails.php
src/Mapper/ProgrammesDbToDomain/OptionsMapper.php

re PROGRAMMES-6886 (Contact pages)
see referencing tickets below

map UGC contact options

---

src/Data/ProgrammesDb/Entity/Contributor.php

for https://github.com/bbc/programmes-faucet/pull/89
re https://jira.dev.bbc.co.uk/browse/PROGRAMMES-7223

increase length of sortName column in Contributor entity

---

README.md
src/Data/ProgrammesDb/Entity/MasterBrand.php
src/Data/ProgrammesDb/EntityRepository/MasterBrandRepository.php
src/Domain/Entity/Season.php
src/Mapper/ProgrammesDbToDomain/CoreEntityMapper.php
src/Service/MasterBrandsService.php
src/Service/ServiceFactory.php
tests/Mapper/ProgrammesDbToDomain/CoreEntityMapperTest.php

adds MasterBrand-related functionality
see https://github.com/bbc/brandingtool-cloud/pull/164

5996 - Brandingtool-specific functionality

---

src/Data/ProgrammesDb/Entity/Ancestry.php
src/Data/ProgrammesDb/EntityRepository/AncestryRepository.php
src/Domain/Entity/Ancestry.php
src/Mapper/ProgrammesDbToDomain/AncestryMapper.php
src/Mapper/ProgrammesDbToDomain/MapperFactory.php
src/Service/AncestryService.php
tests/Data/ProgrammesDb/Entity/AncestryTest.php

Ticket
-----------------
https://jira.dev.bbc.co.uk/browse/DATCAP-1205
Changes
----------------
Created an Ancestry entity.
Created a test file for the Ancestry entity.
Created an Ancestry domain file to establish the ancestry domain.
Created an AncestryRepository file (currently empty), to store ancestry specific queries.
Created an AncestryService file, to allow ancestry instances to be served from the database.
Created an AncestryMapper file to connect the ancestry service to the ancestry entity.
Added the AncestryMapper to the file of avaliable mappers.
Impact
---------------
Ancestry table created in schema. No changes to coreEntity table.
Testing
--------------
The programmes-pages-service build is passing: https://eu-west-1.console.aws.amazon.com/codesuite/codebuild/288896551516/pro …

DATCAP-1205: Create Ancestry Entity
